const SAMPLE = `[{Slot: 0b, id: "minecraft:diamond_sword", count: 1, components: {"minecraft:damage": 34}}]`;

document.getElementById("jsonInput").value = SAMPLE;

// ---------- lenient SNBT-ish -> JSON ----------
function relaxedToJSON(str) {
  let s = str.trim();
  s = s.replace(/([{,]\s*)([A-Za-z_][A-Za-z0-9_]*)\s*:/g, '$1"$2":');
  s = s.replace(/(-?\d+(?:\.\d+)?)[bslfdBSLFD]\b/g, "$1");
  s = s.replace(/,(\s*[}\]])/g, "$1");
  return s;
}
// ---------- icons texture version -------------
const TEXTURE_VERSION = "1.21.11";

// ---------- real texture lookup (extracted vanilla Minecraft item/block icons) ----------
const TEXTURE_BASE = `https://raw.githubusercontent.com/PrismarineJS/minecraft-assets/master/data/${TEXTURE_VERSION}/`;
const ITEM_TABLE = {
  stone: "block/stone",
  granite: "block/granite",
  polished_granite: "block/polished_granite",
  diorite: "block/diorite",
  polished_diorite: "block/polished_diorite",
  andesite: "block/andesite",
  polished_andesite: "block/polished_andesite",
  deepslate: "block/deepslate_top",
  cobbled_deepslate: "block/cobbled_deepslate",
  polished_deepslate: "block/polished_deepslate",
  calcite: "block/calcite",
  tuff: "block/tuff",
  tuff_slab: "block/tuff",
  tuff_stairs: "block/tuff",
  tuff_wall: "block/tuff",
  chiseled_tuff: "block/chiseled_tuff_top",
  polished_tuff: "block/polished_tuff",
  polished_tuff_slab: "block/polished_tuff",
  polished_tuff_stairs: "block/polished_tuff",
  polished_tuff_wall: "block/polished_tuff",
  tuff_bricks: "block/tuff_bricks",
  tuff_brick_slab: "block/tuff_bricks",
  tuff_brick_stairs: "block/tuff_bricks",
  tuff_brick_wall: "block/tuff_bricks",
  chiseled_tuff_bricks: "block/chiseled_tuff_bricks_top",
  dripstone_block: "block/dripstone_block",
  grass_block: "block/dirt",
  dirt: "block/dirt",
  coarse_dirt: "block/coarse_dirt",
  podzol: "block/dirt",
  rooted_dirt: "block/rooted_dirt",
  mud: "block/mud",
  crimson_nylium: "block/netherrack",
  warped_nylium: "block/netherrack",
  cobblestone: "block/cobblestone",
  oak_planks: "block/oak_planks",
  spruce_planks: "block/spruce_planks",
  birch_planks: "block/birch_planks",
  jungle_planks: "block/jungle_planks",
  acacia_planks: "block/acacia_planks",
  cherry_planks: "block/cherry_planks",
  dark_oak_planks: "block/dark_oak_planks",
  mangrove_planks: "block/mangrove_planks",
  bamboo_planks: "block/bamboo_planks",
  crimson_planks: "block/crimson_planks",
  warped_planks: "block/warped_planks",
  bamboo_mosaic: "block/bamboo_mosaic",
  oak_sapling: "block/oak_sapling",
  spruce_sapling: "block/spruce_sapling",
  birch_sapling: "block/birch_sapling",
  jungle_sapling: "block/jungle_sapling",
  acacia_sapling: "block/acacia_sapling",
  cherry_sapling: "block/cherry_sapling",
  dark_oak_sapling: "block/dark_oak_sapling",
  mangrove_propagule: "items/mangrove_propagule",
  bedrock: "block/bedrock",
  sand: "block/sand",
  suspicious_sand: "block/suspicious_sand_0",
  suspicious_gravel: "block/suspicious_gravel_0",
  red_sand: "block/red_sand",
  gravel: "block/gravel",
  coal_ore: "block/coal_ore",
  deepslate_coal_ore: "block/deepslate_coal_ore",
  iron_ore: "block/iron_ore",
  deepslate_iron_ore: "block/deepslate_iron_ore",
  copper_ore: "block/copper_ore",
  deepslate_copper_ore: "block/deepslate_copper_ore",
  gold_ore: "block/gold_ore",
  deepslate_gold_ore: "block/deepslate_gold_ore",
  redstone_ore: "block/redstone_ore",
  deepslate_redstone_ore: "block/deepslate_redstone_ore",
  emerald_ore: "block/emerald_ore",
  deepslate_emerald_ore: "block/deepslate_emerald_ore",
  lapis_ore: "block/lapis_ore",
  deepslate_lapis_ore: "block/deepslate_lapis_ore",
  diamond_ore: "block/diamond_ore",
  deepslate_diamond_ore: "block/deepslate_diamond_ore",
  nether_gold_ore: "block/nether_gold_ore",
  nether_quartz_ore: "block/nether_quartz_ore",
  ancient_debris: "block/ancient_debris_top",
  coal_block: "block/coal_block",
  raw_iron_block: "block/raw_iron_block",
  raw_copper_block: "block/raw_copper_block",
  raw_gold_block: "block/raw_gold_block",
  heavy_core: "block/heavy_core",
  amethyst_block: "block/amethyst_block",
  budding_amethyst: "block/budding_amethyst",
  iron_block: "block/iron_block",
  copper_block: "block/copper_block",
  gold_block: "block/gold_block",
  diamond_block: "block/diamond_block",
  netherite_block: "block/netherite_block",
  exposed_copper: "block/exposed_copper",
  weathered_copper: "block/weathered_copper",
  oxidized_copper: "block/oxidized_copper",
  chiseled_copper: "block/chiseled_copper",
  exposed_chiseled_copper: "block/exposed_chiseled_copper",
  weathered_chiseled_copper: "block/weathered_chiseled_copper",
  oxidized_chiseled_copper: "block/oxidized_chiseled_copper",
  cut_copper: "block/cut_copper",
  exposed_cut_copper: "block/exposed_cut_copper",
  weathered_cut_copper: "block/weathered_cut_copper",
  oxidized_cut_copper: "block/oxidized_cut_copper",
  cut_copper_stairs: "block/cut_copper",
  exposed_cut_copper_stairs: "block/exposed_cut_copper",
  weathered_cut_copper_stairs: "block/weathered_cut_copper",
  oxidized_cut_copper_stairs: "block/oxidized_cut_copper",
  cut_copper_slab: "block/cut_copper",
  exposed_cut_copper_slab: "block/exposed_cut_copper",
  weathered_cut_copper_slab: "block/weathered_cut_copper",
  oxidized_cut_copper_slab: "block/oxidized_cut_copper",
  waxed_copper_block: "block/copper_block",
  waxed_exposed_copper: "block/exposed_copper",
  waxed_weathered_copper: "block/weathered_copper",
  waxed_oxidized_copper: "block/oxidized_copper",
  waxed_chiseled_copper: "block/chiseled_copper",
  waxed_exposed_chiseled_copper: "block/exposed_chiseled_copper",
  waxed_weathered_chiseled_copper: "block/weathered_chiseled_copper",
  waxed_oxidized_chiseled_copper: "block/oxidized_chiseled_copper",
  waxed_cut_copper: "block/cut_copper",
  waxed_exposed_cut_copper: "block/exposed_cut_copper",
  waxed_weathered_cut_copper: "block/weathered_cut_copper",
  waxed_oxidized_cut_copper: "block/oxidized_cut_copper",
  waxed_cut_copper_stairs: "block/cut_copper",
  waxed_exposed_cut_copper_stairs: "block/exposed_cut_copper",
  waxed_weathered_cut_copper_stairs: "block/weathered_cut_copper",
  waxed_oxidized_cut_copper_stairs: "block/oxidized_cut_copper",
  waxed_cut_copper_slab: "block/cut_copper",
  waxed_exposed_cut_copper_slab: "block/exposed_cut_copper",
  waxed_weathered_cut_copper_slab: "block/weathered_cut_copper",
  waxed_oxidized_cut_copper_slab: "block/oxidized_cut_copper",
  oak_log: "block/oak_log_top",
  spruce_log: "block/spruce_log_top",
  birch_log: "block/birch_log_top",
  jungle_log: "block/jungle_log_top",
  acacia_log: "block/acacia_log_top",
  cherry_log: "block/cherry_log_top",
  dark_oak_log: "block/dark_oak_log_top",
  mangrove_log: "block/mangrove_log_top",
  mangrove_roots: "block/mangrove_roots_side",
  muddy_mangrove_roots: "block/muddy_mangrove_roots_top",
  crimson_stem: "block/crimson_stem_top",
  warped_stem: "block/warped_stem_top",
  bamboo_block: "block/bamboo_block_top",
  stripped_oak_log: "block/stripped_oak_log_top",
  stripped_spruce_log: "block/stripped_spruce_log_top",
  stripped_birch_log: "block/stripped_birch_log_top",
  stripped_jungle_log: "block/stripped_jungle_log_top",
  stripped_acacia_log: "block/stripped_acacia_log_top",
  stripped_cherry_log: "block/stripped_cherry_log_top",
  stripped_dark_oak_log: "block/stripped_dark_oak_log_top",
  stripped_mangrove_log: "block/stripped_mangrove_log_top",
  stripped_crimson_stem: "block/stripped_crimson_stem_top",
  stripped_warped_stem: "block/stripped_warped_stem_top",
  stripped_oak_wood: "block/stripped_oak_log",
  stripped_spruce_wood: "block/stripped_spruce_log",
  stripped_birch_wood: "block/stripped_birch_log",
  stripped_jungle_wood: "block/stripped_jungle_log",
  stripped_acacia_wood: "block/stripped_acacia_log",
  stripped_cherry_wood: "block/stripped_cherry_log",
  stripped_dark_oak_wood: "block/stripped_dark_oak_log",
  stripped_mangrove_wood: "block/stripped_mangrove_log",
  stripped_crimson_hyphae: "block/stripped_crimson_stem",
  stripped_warped_hyphae: "block/stripped_warped_stem",
  stripped_bamboo_block: "block/stripped_bamboo_block_top",
  oak_wood: "block/oak_log",
  spruce_wood: "block/spruce_log",
  birch_wood: "block/birch_log",
  jungle_wood: "block/jungle_log",
  acacia_wood: "block/acacia_log",
  cherry_wood: "block/cherry_log",
  dark_oak_wood: "block/dark_oak_log",
  mangrove_wood: "block/mangrove_log",
  crimson_hyphae: "block/crimson_stem",
  warped_hyphae: "block/warped_stem",
  oak_leaves: "block/oak_leaves",
  spruce_leaves: "block/spruce_leaves",
  birch_leaves: "block/birch_leaves",
  jungle_leaves: "block/jungle_leaves",
  acacia_leaves: "block/acacia_leaves",
  cherry_leaves: "block/cherry_leaves",
  dark_oak_leaves: "block/dark_oak_leaves",
  mangrove_leaves: "block/mangrove_leaves",
  azalea_leaves: "block/azalea_leaves",
  flowering_azalea_leaves: "block/flowering_azalea_leaves",
  sponge: "block/sponge",
  wet_sponge: "block/wet_sponge",
  glass: "block/glass",
  tinted_glass: "block/tinted_glass",
  lapis_block: "block/lapis_block",
  sandstone: "block/sandstone_bottom",
  chiseled_sandstone: "block/sandstone_top",
  cut_sandstone: "block/sandstone_top",
  cobweb: "block/cobweb",
  short_grass: "block/short_grass",
  fern: "block/fern",
  azalea: "block/azalea_side",
  flowering_azalea: "block/flowering_azalea_side",
  dead_bush: "block/dead_bush",
  seagrass: "items/seagrass",
  sea_pickle: "items/sea_pickle",
  white_wool: "block/white_wool",
  orange_wool: "block/orange_wool",
  magenta_wool: "block/magenta_wool",
  light_blue_wool: "block/light_blue_wool",
  yellow_wool: "block/yellow_wool",
  lime_wool: "block/lime_wool",
  pink_wool: "block/pink_wool",
  gray_wool: "block/gray_wool",
  light_gray_wool: "block/light_gray_wool",
  cyan_wool: "block/cyan_wool",
  purple_wool: "block/purple_wool",
  blue_wool: "block/blue_wool",
  brown_wool: "block/brown_wool",
  green_wool: "block/green_wool",
  red_wool: "block/red_wool",
  black_wool: "block/black_wool",
  dandelion: "block/dandelion",
  poppy: "block/poppy",
  blue_orchid: "block/blue_orchid",
  allium: "block/allium",
  azure_bluet: "block/azure_bluet",
  red_tulip: "block/red_tulip",
  orange_tulip: "block/orange_tulip",
  white_tulip: "block/white_tulip",
  pink_tulip: "block/pink_tulip",
  oxeye_daisy: "block/oxeye_daisy",
  cornflower: "block/cornflower",
  lily_of_the_valley: "block/lily_of_the_valley",
  wither_rose: "block/wither_rose",
  torchflower: "block/torchflower",
  pitcher_plant: "items/pitcher_plant",
  spore_blossom: "block/spore_blossom",
  brown_mushroom: "block/brown_mushroom",
  red_mushroom: "block/red_mushroom",
  crimson_fungus: "block/crimson_fungus",
  warped_fungus: "block/warped_fungus",
  crimson_roots: "block/crimson_roots",
  warped_roots: "block/warped_roots",
  nether_sprouts: "items/nether_sprouts",
  weeping_vines: "block/weeping_vines_plant",
  twisting_vines: "block/twisting_vines_plant",
  sugar_cane: "items/sugar_cane",
  kelp: "items/kelp",
  moss_carpet: "block/moss_block",
  pink_petals: "items/pink_petals",
  moss_block: "block/moss_block",
  hanging_roots: "block/hanging_roots",
  big_dripleaf: "block/big_dripleaf_top",
  small_dripleaf: "block/small_dripleaf_top",
  bamboo: "items/bamboo",
  oak_slab: "block/oak_planks",
  spruce_slab: "block/spruce_planks",
  birch_slab: "block/birch_planks",
  jungle_slab: "block/jungle_planks",
  acacia_slab: "block/acacia_planks",
  cherry_slab: "block/cherry_planks",
  dark_oak_slab: "block/dark_oak_planks",
  mangrove_slab: "block/mangrove_planks",
  bamboo_slab: "block/bamboo_planks",
  bamboo_mosaic_slab: "block/bamboo_mosaic",
  crimson_slab: "block/crimson_planks",
  warped_slab: "block/warped_planks",
  stone_slab: "block/stone",
  smooth_stone_slab: "block/smooth_stone",
  sandstone_slab: "block/sandstone_bottom",
  cut_sandstone_slab: "block/sandstone_top",
  petrified_oak_slab: "block/oak_planks",
  cobblestone_slab: "block/cobblestone",
  brick_slab: "block/bricks",
  stone_brick_slab: "block/stone_bricks",
  mud_brick_slab: "block/mud_bricks",
  nether_brick_slab: "block/nether_bricks",
  quartz_slab: "block/quartz_block_top",
  red_sandstone_slab: "block/red_sandstone_bottom",
  cut_red_sandstone_slab: "block/red_sandstone_top",
  purpur_slab: "block/purpur_block",
  prismarine_slab: "block/prismarine",
  prismarine_brick_slab: "block/prismarine_bricks",
  dark_prismarine_slab: "block/dark_prismarine",
  smooth_quartz: "block/quartz_block_bottom",
  smooth_red_sandstone: "block/red_sandstone_top",
  smooth_sandstone: "block/sandstone_top",
  smooth_stone: "block/smooth_stone",
  bricks: "block/bricks",
  bookshelf: "block/oak_planks",
  chiseled_bookshelf: "block/chiseled_bookshelf_top",
  mossy_cobblestone: "block/mossy_cobblestone",
  obsidian: "block/obsidian",
  torch: "block/torch",
  end_rod: "block/end_rod",
  chorus_plant: "block/chorus_plant",
  chorus_flower: "block/chorus_flower",
  purpur_block: "block/purpur_block",
  purpur_pillar: "block/purpur_pillar_top",
  purpur_stairs: "block/purpur_block",
  spawner: "block/spawner",
  chest: "block/oak_planks",
  crafting_table: "block/oak_planks",
  farmland: "block/dirt",
  furnace: "block/furnace_front",
  ladder: "block/ladder",
  cobblestone_stairs: "block/cobblestone",
  snow: "block/snow",
  ice: "block/ice",
  snow_block: "block/snow",
  cactus: "block/cactus_side",
  clay: "block/clay",
  jukebox: "block/jukebox_side",
  oak_fence: "block/oak_planks",
  spruce_fence: "block/spruce_planks",
  birch_fence: "block/birch_planks",
  jungle_fence: "block/jungle_planks",
  acacia_fence: "block/acacia_planks",
  cherry_fence: "block/cherry_planks",
  dark_oak_fence: "block/dark_oak_planks",
  mangrove_fence: "block/mangrove_planks",
  bamboo_fence: "block/bamboo_fence",
  crimson_fence: "block/crimson_planks",
  warped_fence: "block/warped_planks",
  pumpkin: "block/pumpkin_top",
  carved_pumpkin: "block/carved_pumpkin",
  jack_o_lantern: "block/jack_o_lantern",
  netherrack: "block/netherrack",
  soul_sand: "block/soul_sand",
  soul_soil: "block/soul_soil",
  basalt: "block/basalt_top",
  polished_basalt: "block/polished_basalt_top",
  smooth_basalt: "block/smooth_basalt",
  soul_torch: "block/soul_torch",
  glowstone: "block/glowstone",
  infested_stone: "block/stone",
  infested_cobblestone: "block/cobblestone",
  infested_stone_bricks: "block/stone_bricks",
  infested_mossy_stone_bricks: "block/mossy_stone_bricks",
  infested_cracked_stone_bricks: "block/cracked_stone_bricks",
  infested_chiseled_stone_bricks: "block/chiseled_stone_bricks",
  infested_deepslate: "block/deepslate_top",
  stone_bricks: "block/stone_bricks",
  mossy_stone_bricks: "block/mossy_stone_bricks",
  cracked_stone_bricks: "block/cracked_stone_bricks",
  chiseled_stone_bricks: "block/chiseled_stone_bricks",
  packed_mud: "block/packed_mud",
  mud_bricks: "block/mud_bricks",
  deepslate_bricks: "block/deepslate_bricks",
  cracked_deepslate_bricks: "block/cracked_deepslate_bricks",
  deepslate_tiles: "block/deepslate_tiles",
  cracked_deepslate_tiles: "block/cracked_deepslate_tiles",
  chiseled_deepslate: "block/chiseled_deepslate",
  reinforced_deepslate: "block/reinforced_deepslate_bottom",
  brown_mushroom_block: "block/brown_mushroom_block",
  red_mushroom_block: "block/red_mushroom_block",
  mushroom_stem: "block/mushroom_stem",
  iron_bars: "block/iron_bars",
  chain: "items/chain",
  glass_pane: "block/glass",
  melon: "block/melon_top",
  vine: "block/vine",
  glow_lichen: "block/glow_lichen",
  brick_stairs: "block/bricks",
  stone_brick_stairs: "block/stone_bricks",
  mud_brick_stairs: "block/mud_bricks",
  mycelium: "block/dirt",
  lily_pad: "block/lily_pad",
  nether_bricks: "block/nether_bricks",
  cracked_nether_bricks: "block/cracked_nether_bricks",
  chiseled_nether_bricks: "block/chiseled_nether_bricks",
  nether_brick_fence: "block/nether_bricks",
  nether_brick_stairs: "block/nether_bricks",
  sculk: "block/sculk",
  sculk_vein: "block/sculk_vein",
  sculk_catalyst: "block/sculk_catalyst_bottom",
  sculk_shrieker: "block/sculk_shrieker_bottom",
  enchanting_table: "block/enchanting_table_bottom",
  end_portal_frame: "block/end_portal_frame_side",
  end_stone: "block/end_stone",
  end_stone_bricks: "block/end_stone_bricks",
  dragon_egg: "block/dragon_egg",
  sandstone_stairs: "block/sandstone_bottom",
  ender_chest: "block/obsidian",
  emerald_block: "block/emerald_block",
  oak_stairs: "block/oak_planks",
  spruce_stairs: "block/spruce_planks",
  birch_stairs: "block/birch_planks",
  jungle_stairs: "block/jungle_planks",
  acacia_stairs: "block/acacia_planks",
  cherry_stairs: "block/cherry_planks",
  dark_oak_stairs: "block/dark_oak_planks",
  mangrove_stairs: "block/mangrove_planks",
  bamboo_stairs: "block/bamboo_planks",
  bamboo_mosaic_stairs: "block/bamboo_mosaic",
  crimson_stairs: "block/crimson_planks",
  warped_stairs: "block/warped_planks",
  command_block: "block/command_block_back",
  beacon: "block/glass",
  cobblestone_wall: "block/cobblestone",
  mossy_cobblestone_wall: "block/mossy_cobblestone",
  brick_wall: "block/bricks",
  prismarine_wall: "block/prismarine",
  red_sandstone_wall: "block/red_sandstone",
  mossy_stone_brick_wall: "block/mossy_stone_bricks",
  granite_wall: "block/granite",
  stone_brick_wall: "block/stone_bricks",
  mud_brick_wall: "block/mud_bricks",
  nether_brick_wall: "block/nether_bricks",
  andesite_wall: "block/andesite",
  red_nether_brick_wall: "block/red_nether_bricks",
  sandstone_wall: "block/sandstone",
  end_stone_brick_wall: "block/end_stone_bricks",
  diorite_wall: "block/diorite",
  blackstone_wall: "block/blackstone",
  polished_blackstone_wall: "block/polished_blackstone",
  polished_blackstone_brick_wall: "block/polished_blackstone_bricks",
  cobbled_deepslate_wall: "block/cobbled_deepslate",
  polished_deepslate_wall: "block/polished_deepslate",
  deepslate_brick_wall: "block/deepslate_bricks",
  deepslate_tile_wall: "block/deepslate_tiles",
  anvil: "block/anvil_top",
  chipped_anvil: "block/chipped_anvil_top",
  damaged_anvil: "block/damaged_anvil_top",
  chiseled_quartz_block: "block/chiseled_quartz_block_top",
  quartz_block: "block/quartz_block_top",
  quartz_bricks: "block/quartz_bricks",
  quartz_pillar: "block/quartz_pillar_top",
  quartz_stairs: "block/quartz_block_top",
  white_terracotta: "block/white_terracotta",
  orange_terracotta: "block/orange_terracotta",
  magenta_terracotta: "block/magenta_terracotta",
  light_blue_terracotta: "block/light_blue_terracotta",
  yellow_terracotta: "block/yellow_terracotta",
  lime_terracotta: "block/lime_terracotta",
  pink_terracotta: "block/pink_terracotta",
  gray_terracotta: "block/gray_terracotta",
  light_gray_terracotta: "block/light_gray_terracotta",
  cyan_terracotta: "block/cyan_terracotta",
  purple_terracotta: "block/purple_terracotta",
  blue_terracotta: "block/blue_terracotta",
  brown_terracotta: "block/brown_terracotta",
  green_terracotta: "block/green_terracotta",
  red_terracotta: "block/red_terracotta",
  black_terracotta: "block/black_terracotta",
  barrier: "items/barrier",
  light: "items/light",
  hay_block: "block/hay_block_top",
  white_carpet: "block/white_wool",
  orange_carpet: "block/orange_wool",
  magenta_carpet: "block/magenta_wool",
  light_blue_carpet: "block/light_blue_wool",
  yellow_carpet: "block/yellow_wool",
  lime_carpet: "block/lime_wool",
  pink_carpet: "block/pink_wool",
  gray_carpet: "block/gray_wool",
  light_gray_carpet: "block/light_gray_wool",
  cyan_carpet: "block/cyan_wool",
  purple_carpet: "block/purple_wool",
  blue_carpet: "block/blue_wool",
  brown_carpet: "block/brown_wool",
  green_carpet: "block/green_wool",
  red_carpet: "block/red_wool",
  black_carpet: "block/black_wool",
  terracotta: "block/terracotta",
  packed_ice: "block/packed_ice",
  dirt_path: "block/dirt",
  sunflower: "block/sunflower_front",
  lilac: "block/lilac_top",
  rose_bush: "block/rose_bush_top",
  peony: "block/peony_top",
  tall_grass: "block/tall_grass_top",
  large_fern: "block/large_fern_top",
  white_stained_glass: "block/white_stained_glass",
  orange_stained_glass: "block/orange_stained_glass",
  magenta_stained_glass: "block/magenta_stained_glass",
  light_blue_stained_glass: "block/light_blue_stained_glass",
  yellow_stained_glass: "block/yellow_stained_glass",
  lime_stained_glass: "block/lime_stained_glass",
  pink_stained_glass: "block/pink_stained_glass",
  gray_stained_glass: "block/gray_stained_glass",
  light_gray_stained_glass: "block/light_gray_stained_glass",
  cyan_stained_glass: "block/cyan_stained_glass",
  purple_stained_glass: "block/purple_stained_glass",
  blue_stained_glass: "block/blue_stained_glass",
  brown_stained_glass: "block/brown_stained_glass",
  green_stained_glass: "block/green_stained_glass",
  red_stained_glass: "block/red_stained_glass",
  black_stained_glass: "block/black_stained_glass",
  white_stained_glass_pane: "block/white_stained_glass",
  orange_stained_glass_pane: "block/orange_stained_glass",
  magenta_stained_glass_pane: "block/magenta_stained_glass",
  light_blue_stained_glass_pane: "block/light_blue_stained_glass",
  yellow_stained_glass_pane: "block/yellow_stained_glass",
  lime_stained_glass_pane: "block/lime_stained_glass",
  pink_stained_glass_pane: "block/pink_stained_glass",
  gray_stained_glass_pane: "block/gray_stained_glass",
  light_gray_stained_glass_pane: "block/light_gray_stained_glass",
  cyan_stained_glass_pane: "block/cyan_stained_glass",
  purple_stained_glass_pane: "block/purple_stained_glass",
  blue_stained_glass_pane: "block/blue_stained_glass",
  brown_stained_glass_pane: "block/brown_stained_glass",
  green_stained_glass_pane: "block/green_stained_glass",
  red_stained_glass_pane: "block/red_stained_glass",
  black_stained_glass_pane: "block/black_stained_glass",
  prismarine: "block/prismarine",
  prismarine_bricks: "block/prismarine_bricks",
  dark_prismarine: "block/dark_prismarine",
  prismarine_stairs: "block/prismarine",
  prismarine_brick_stairs: "block/prismarine_bricks",
  dark_prismarine_stairs: "block/dark_prismarine",
  sea_lantern: "block/sea_lantern",
  red_sandstone: "block/red_sandstone_bottom",
  chiseled_red_sandstone: "block/red_sandstone_top",
  cut_red_sandstone: "block/red_sandstone_top",
  red_sandstone_stairs: "block/red_sandstone_bottom",
  repeating_command_block: "block/repeating_command_block_back",
  chain_command_block: "block/chain_command_block_back",
  magma_block: "block/magma",
  nether_wart_block: "block/nether_wart_block",
  warped_wart_block: "block/warped_wart_block",
  red_nether_bricks: "block/red_nether_bricks",
  bone_block: "block/bone_block_top",
  structure_void: "items/structure_void",
  shulker_box: "block/shulker_box",
  white_shulker_box: "block/white_shulker_box",
  orange_shulker_box: "block/orange_shulker_box",
  magenta_shulker_box: "block/magenta_shulker_box",
  light_blue_shulker_box: "block/light_blue_shulker_box",
  yellow_shulker_box: "block/yellow_shulker_box",
  lime_shulker_box: "block/lime_shulker_box",
  pink_shulker_box: "block/pink_shulker_box",
  gray_shulker_box: "block/gray_shulker_box",
  light_gray_shulker_box: "block/light_gray_shulker_box",
  cyan_shulker_box: "block/cyan_shulker_box",
  purple_shulker_box: "block/purple_shulker_box",
  blue_shulker_box: "block/blue_shulker_box",
  brown_shulker_box: "block/brown_shulker_box",
  green_shulker_box: "block/green_shulker_box",
  red_shulker_box: "block/red_shulker_box",
  black_shulker_box: "block/black_shulker_box",
  white_glazed_terracotta: "block/white_glazed_terracotta",
  orange_glazed_terracotta: "block/orange_glazed_terracotta",
  magenta_glazed_terracotta: "block/magenta_glazed_terracotta",
  light_blue_glazed_terracotta: "block/light_blue_glazed_terracotta",
  yellow_glazed_terracotta: "block/yellow_glazed_terracotta",
  lime_glazed_terracotta: "block/lime_glazed_terracotta",
  pink_glazed_terracotta: "block/pink_glazed_terracotta",
  gray_glazed_terracotta: "block/gray_glazed_terracotta",
  light_gray_glazed_terracotta: "block/light_gray_glazed_terracotta",
  cyan_glazed_terracotta: "block/cyan_glazed_terracotta",
  purple_glazed_terracotta: "block/purple_glazed_terracotta",
  blue_glazed_terracotta: "block/blue_glazed_terracotta",
  brown_glazed_terracotta: "block/brown_glazed_terracotta",
  green_glazed_terracotta: "block/green_glazed_terracotta",
  red_glazed_terracotta: "block/red_glazed_terracotta",
  black_glazed_terracotta: "block/black_glazed_terracotta",
  white_concrete: "block/white_concrete",
  orange_concrete: "block/orange_concrete",
  magenta_concrete: "block/magenta_concrete",
  light_blue_concrete: "block/light_blue_concrete",
  yellow_concrete: "block/yellow_concrete",
  lime_concrete: "block/lime_concrete",
  pink_concrete: "block/pink_concrete",
  gray_concrete: "block/gray_concrete",
  light_gray_concrete: "block/light_gray_concrete",
  cyan_concrete: "block/cyan_concrete",
  purple_concrete: "block/purple_concrete",
  blue_concrete: "block/blue_concrete",
  brown_concrete: "block/brown_concrete",
  green_concrete: "block/green_concrete",
  red_concrete: "block/red_concrete",
  black_concrete: "block/black_concrete",
  white_concrete_powder: "block/white_concrete_powder",
  orange_concrete_powder: "block/orange_concrete_powder",
  magenta_concrete_powder: "block/magenta_concrete_powder",
  light_blue_concrete_powder: "block/light_blue_concrete_powder",
  yellow_concrete_powder: "block/yellow_concrete_powder",
  lime_concrete_powder: "block/lime_concrete_powder",
  pink_concrete_powder: "block/pink_concrete_powder",
  gray_concrete_powder: "block/gray_concrete_powder",
  light_gray_concrete_powder: "block/light_gray_concrete_powder",
  cyan_concrete_powder: "block/cyan_concrete_powder",
  purple_concrete_powder: "block/purple_concrete_powder",
  blue_concrete_powder: "block/blue_concrete_powder",
  brown_concrete_powder: "block/brown_concrete_powder",
  green_concrete_powder: "block/green_concrete_powder",
  red_concrete_powder: "block/red_concrete_powder",
  black_concrete_powder: "block/black_concrete_powder",
  turtle_egg: "items/turtle_egg",
  sniffer_egg: "items/sniffer_egg",
  dead_tube_coral_block: "block/dead_tube_coral_block",
  dead_brain_coral_block: "block/dead_brain_coral_block",
  dead_bubble_coral_block: "block/dead_bubble_coral_block",
  dead_fire_coral_block: "block/dead_fire_coral_block",
  dead_horn_coral_block: "block/dead_horn_coral_block",
  tube_coral_block: "block/tube_coral_block",
  brain_coral_block: "block/brain_coral_block",
  bubble_coral_block: "block/bubble_coral_block",
  fire_coral_block: "block/fire_coral_block",
  horn_coral_block: "block/horn_coral_block",
  tube_coral: "block/tube_coral",
  brain_coral: "block/brain_coral",
  bubble_coral: "block/bubble_coral",
  fire_coral: "block/fire_coral",
  horn_coral: "block/horn_coral",
  dead_brain_coral: "block/dead_brain_coral",
  dead_bubble_coral: "block/dead_bubble_coral",
  dead_fire_coral: "block/dead_fire_coral",
  dead_horn_coral: "block/dead_horn_coral",
  dead_tube_coral: "block/dead_tube_coral",
  tube_coral_fan: "block/tube_coral_fan",
  brain_coral_fan: "block/brain_coral_fan",
  bubble_coral_fan: "block/bubble_coral_fan",
  fire_coral_fan: "block/fire_coral_fan",
  horn_coral_fan: "block/horn_coral_fan",
  dead_tube_coral_fan: "block/dead_tube_coral_fan",
  dead_brain_coral_fan: "block/dead_brain_coral_fan",
  dead_bubble_coral_fan: "block/dead_bubble_coral_fan",
  dead_fire_coral_fan: "block/dead_fire_coral_fan",
  dead_horn_coral_fan: "block/dead_horn_coral_fan",
  blue_ice: "block/blue_ice",
  conduit: "block/conduit",
  polished_granite_stairs: "block/polished_granite",
  smooth_red_sandstone_stairs: "block/red_sandstone_top",
  mossy_stone_brick_stairs: "block/mossy_stone_bricks",
  polished_diorite_stairs: "block/polished_diorite",
  mossy_cobblestone_stairs: "block/mossy_cobblestone",
  end_stone_brick_stairs: "block/end_stone_bricks",
  stone_stairs: "block/stone",
  smooth_sandstone_stairs: "block/sandstone_top",
  smooth_quartz_stairs: "block/quartz_block_bottom",
  granite_stairs: "block/granite",
  andesite_stairs: "block/andesite",
  red_nether_brick_stairs: "block/red_nether_bricks",
  polished_andesite_stairs: "block/polished_andesite",
  diorite_stairs: "block/diorite",
  cobbled_deepslate_stairs: "block/cobbled_deepslate",
  polished_deepslate_stairs: "block/polished_deepslate",
  deepslate_brick_stairs: "block/deepslate_bricks",
  deepslate_tile_stairs: "block/deepslate_tiles",
  polished_granite_slab: "block/polished_granite",
  smooth_red_sandstone_slab: "block/red_sandstone_top",
  mossy_stone_brick_slab: "block/mossy_stone_bricks",
  polished_diorite_slab: "block/polished_diorite",
  mossy_cobblestone_slab: "block/mossy_cobblestone",
  end_stone_brick_slab: "block/end_stone_bricks",
  smooth_sandstone_slab: "block/sandstone_top",
  smooth_quartz_slab: "block/quartz_block_bottom",
  granite_slab: "block/granite",
  andesite_slab: "block/andesite",
  red_nether_brick_slab: "block/red_nether_bricks",
  polished_andesite_slab: "block/polished_andesite",
  diorite_slab: "block/diorite",
  cobbled_deepslate_slab: "block/cobbled_deepslate",
  polished_deepslate_slab: "block/polished_deepslate",
  deepslate_brick_slab: "block/deepslate_bricks",
  deepslate_tile_slab: "block/deepslate_tiles",
  scaffolding: "block/scaffolding_top",
  redstone: "items/redstone",
  redstone_torch: "block/redstone_torch",
  redstone_block: "block/redstone_block",
  repeater: "items/repeater",
  comparator: "items/comparator",
  piston: "block/piston_bottom",
  sticky_piston: "block/piston_bottom",
  slime_block: "block/slime_block",
  honey_block: "block/honey_block_top",
  observer: "block/observer_back",
  hopper: "items/hopper",
  dispenser: "block/dispenser_front",
  dropper: "block/dropper_front",
  lectern: "block/lectern_sides",
  target: "block/target_top",
  lever: "block/lever",
  lightning_rod: "block/lightning_rod",
  daylight_detector: "block/daylight_detector_side",
  sculk_sensor: "block/sculk_sensor_tendril_inactive",
  calibrated_sculk_sensor: "block/sculk_sensor_tendril_inactive",
  tripwire_hook: "block/tripwire_hook",
  trapped_chest: "block/oak_planks",
  tnt: "block/tnt_bottom",
  redstone_lamp: "block/redstone_lamp",
  note_block: "block/note_block",
  stone_button: "block/stone",
  polished_blackstone_button: "block/polished_blackstone",
  oak_button: "block/oak_planks",
  spruce_button: "block/spruce_planks",
  birch_button: "block/birch_planks",
  jungle_button: "block/jungle_planks",
  acacia_button: "block/acacia_planks",
  cherry_button: "block/cherry_planks",
  dark_oak_button: "block/dark_oak_planks",
  mangrove_button: "block/mangrove_planks",
  bamboo_button: "block/bamboo_planks",
  crimson_button: "block/crimson_planks",
  warped_button: "block/warped_planks",
  stone_pressure_plate: "block/stone",
  polished_blackstone_pressure_plate: "block/polished_blackstone",
  light_weighted_pressure_plate: "block/gold_block",
  heavy_weighted_pressure_plate: "block/iron_block",
  oak_pressure_plate: "block/oak_planks",
  spruce_pressure_plate: "block/spruce_planks",
  birch_pressure_plate: "block/birch_planks",
  jungle_pressure_plate: "block/jungle_planks",
  acacia_pressure_plate: "block/acacia_planks",
  cherry_pressure_plate: "block/cherry_planks",
  dark_oak_pressure_plate: "block/dark_oak_planks",
  mangrove_pressure_plate: "block/mangrove_planks",
  bamboo_pressure_plate: "block/bamboo_planks",
  crimson_pressure_plate: "block/crimson_planks",
  warped_pressure_plate: "block/warped_planks",
  iron_door: "items/iron_door",
  oak_door: "items/oak_door",
  spruce_door: "items/spruce_door",
  birch_door: "items/birch_door",
  jungle_door: "items/jungle_door",
  acacia_door: "items/acacia_door",
  cherry_door: "items/cherry_door",
  dark_oak_door: "items/dark_oak_door",
  mangrove_door: "items/mangrove_door",
  bamboo_door: "items/bamboo_door",
  crimson_door: "items/crimson_door",
  warped_door: "items/warped_door",
  copper_door: "items/copper_door",
  exposed_copper_door: "items/exposed_copper_door",
  weathered_copper_door: "items/weathered_copper_door",
  oxidized_copper_door: "items/oxidized_copper_door",
  waxed_copper_door: "items/copper_door",
  waxed_exposed_copper_door: "items/exposed_copper_door",
  waxed_weathered_copper_door: "items/weathered_copper_door",
  waxed_oxidized_copper_door: "items/oxidized_copper_door",
  iron_trapdoor: "block/iron_trapdoor",
  oak_trapdoor: "block/oak_trapdoor",
  spruce_trapdoor: "block/spruce_trapdoor",
  birch_trapdoor: "block/birch_trapdoor",
  jungle_trapdoor: "block/jungle_trapdoor",
  acacia_trapdoor: "block/acacia_trapdoor",
  cherry_trapdoor: "block/cherry_trapdoor",
  dark_oak_trapdoor: "block/dark_oak_trapdoor",
  mangrove_trapdoor: "block/mangrove_trapdoor",
  bamboo_trapdoor: "block/bamboo_trapdoor",
  crimson_trapdoor: "block/crimson_trapdoor",
  warped_trapdoor: "block/warped_trapdoor",
  copper_trapdoor: "block/copper_trapdoor",
  exposed_copper_trapdoor: "block/exposed_copper_trapdoor",
  weathered_copper_trapdoor: "block/weathered_copper_trapdoor",
  oxidized_copper_trapdoor: "block/oxidized_copper_trapdoor",
  waxed_copper_trapdoor: "block/copper_trapdoor",
  waxed_exposed_copper_trapdoor: "block/exposed_copper_trapdoor",
  waxed_weathered_copper_trapdoor: "block/weathered_copper_trapdoor",
  waxed_oxidized_copper_trapdoor: "block/oxidized_copper_trapdoor",
  oak_fence_gate: "block/oak_planks",
  spruce_fence_gate: "block/spruce_planks",
  birch_fence_gate: "block/birch_planks",
  jungle_fence_gate: "block/jungle_planks",
  acacia_fence_gate: "block/acacia_planks",
  cherry_fence_gate: "block/cherry_planks",
  dark_oak_fence_gate: "block/dark_oak_planks",
  mangrove_fence_gate: "block/mangrove_planks",
  bamboo_fence_gate: "block/bamboo_fence_gate_particle",
  crimson_fence_gate: "block/crimson_planks",
  warped_fence_gate: "block/warped_planks",
  powered_rail: "block/powered_rail",
  detector_rail: "block/detector_rail",
  rail: "block/rail",
  activator_rail: "block/activator_rail",
  saddle: "items/saddle",
  minecart: "items/minecart",
  chest_minecart: "items/chest_minecart",
  furnace_minecart: "items/furnace_minecart",
  tnt_minecart: "items/tnt_minecart",
  hopper_minecart: "items/hopper_minecart",
  carrot_on_a_stick: "items/carrot_on_a_stick",
  warped_fungus_on_a_stick: "items/warped_fungus_on_a_stick",
  elytra: "items/elytra",
  oak_boat: "items/oak_boat",
  oak_chest_boat: "items/oak_chest_boat",
  spruce_boat: "items/spruce_boat",
  spruce_chest_boat: "items/spruce_chest_boat",
  birch_boat: "items/birch_boat",
  birch_chest_boat: "items/birch_chest_boat",
  jungle_boat: "items/jungle_boat",
  jungle_chest_boat: "items/jungle_chest_boat",
  acacia_boat: "items/acacia_boat",
  acacia_chest_boat: "items/acacia_chest_boat",
  cherry_boat: "items/cherry_boat",
  cherry_chest_boat: "items/cherry_chest_boat",
  dark_oak_boat: "items/dark_oak_boat",
  dark_oak_chest_boat: "items/dark_oak_chest_boat",
  mangrove_boat: "items/mangrove_boat",
  mangrove_chest_boat: "items/mangrove_chest_boat",
  bamboo_raft: "items/bamboo_raft",
  bamboo_chest_raft: "items/bamboo_chest_raft",
  structure_block: "block/structure_block",
  jigsaw: "block/jigsaw_side",
  turtle_helmet: "items/turtle_helmet",
  turtle_scute: "items/turtle_scute",
  armadillo_scute: "items/armadillo_scute",
  wolf_armor: "items/wolf_armor",
  flint_and_steel: "items/flint_and_steel",
  bowl: "items/bowl",
  apple: "items/apple",
  bow: "items/bow",
  arrow: "items/arrow",
  coal: "items/coal",
  charcoal: "items/charcoal",
  diamond: "items/diamond",
  emerald: "items/emerald",
  lapis_lazuli: "items/lapis_lazuli",
  quartz: "items/quartz",
  amethyst_shard: "items/amethyst_shard",
  raw_iron: "items/raw_iron",
  iron_ingot: "items/iron_ingot",
  raw_copper: "items/raw_copper",
  copper_ingot: "items/copper_ingot",
  raw_gold: "items/raw_gold",
  gold_ingot: "items/gold_ingot",
  netherite_ingot: "items/netherite_ingot",
  netherite_scrap: "items/netherite_scrap",
  wooden_sword: "items/wooden_sword",
  wooden_shovel: "items/wooden_shovel",
  wooden_pickaxe: "items/wooden_pickaxe",
  wooden_axe: "items/wooden_axe",
  wooden_hoe: "items/wooden_hoe",
  stone_sword: "items/stone_sword",
  stone_shovel: "items/stone_shovel",
  stone_pickaxe: "items/stone_pickaxe",
  stone_axe: "items/stone_axe",
  stone_hoe: "items/stone_hoe",
  golden_sword: "items/golden_sword",
  golden_shovel: "items/golden_shovel",
  golden_pickaxe: "items/golden_pickaxe",
  golden_axe: "items/golden_axe",
  golden_hoe: "items/golden_hoe",
  iron_sword: "items/iron_sword",
  iron_shovel: "items/iron_shovel",
  iron_pickaxe: "items/iron_pickaxe",
  iron_axe: "items/iron_axe",
  iron_hoe: "items/iron_hoe",
  diamond_sword: "items/diamond_sword",
  diamond_shovel: "items/diamond_shovel",
  diamond_pickaxe: "items/diamond_pickaxe",
  diamond_axe: "items/diamond_axe",
  diamond_hoe: "items/diamond_hoe",
  netherite_sword: "items/netherite_sword",
  netherite_shovel: "items/netherite_shovel",
  netherite_pickaxe: "items/netherite_pickaxe",
  netherite_axe: "items/netherite_axe",
  netherite_hoe: "items/netherite_hoe",
  stick: "items/stick",
  mushroom_stew: "items/mushroom_stew",
  string: "items/string",
  feather: "items/feather",
  gunpowder: "items/gunpowder",
  wheat_seeds: "items/wheat_seeds",
  wheat: "items/wheat",
  bread: "items/bread",
  leather_helmet: "items/leather_helmet",
  leather_chestplate: "items/leather_chestplate",
  leather_leggings: "items/leather_leggings",
  leather_boots: "items/leather_boots",
  chainmail_helmet: "items/chainmail_helmet",
  chainmail_chestplate: "items/chainmail_chestplate",
  chainmail_leggings: "items/chainmail_leggings",
  chainmail_boots: "items/chainmail_boots",
  iron_helmet: "items/iron_helmet",
  iron_chestplate: "items/iron_chestplate",
  iron_leggings: "items/iron_leggings",
  iron_boots: "items/iron_boots",
  diamond_helmet: "items/diamond_helmet",
  diamond_chestplate: "items/diamond_chestplate",
  diamond_leggings: "items/diamond_leggings",
  diamond_boots: "items/diamond_boots",
  golden_helmet: "items/golden_helmet",
  golden_chestplate: "items/golden_chestplate",
  golden_leggings: "items/golden_leggings",
  golden_boots: "items/golden_boots",
  netherite_helmet: "items/netherite_helmet",
  netherite_chestplate: "items/netherite_chestplate",
  netherite_leggings: "items/netherite_leggings",
  netherite_boots: "items/netherite_boots",
  flint: "items/flint",
  porkchop: "items/porkchop",
  cooked_porkchop: "items/cooked_porkchop",
  painting: "items/painting",
  golden_apple: "items/golden_apple",
  enchanted_golden_apple: "items/golden_apple",
  oak_sign: "items/oak_sign",
  spruce_sign: "items/spruce_sign",
  birch_sign: "items/birch_sign",
  jungle_sign: "items/jungle_sign",
  acacia_sign: "items/acacia_sign",
  cherry_sign: "items/cherry_sign",
  dark_oak_sign: "items/dark_oak_sign",
  mangrove_sign: "items/mangrove_sign",
  bamboo_sign: "items/bamboo_sign",
  crimson_sign: "items/crimson_sign",
  warped_sign: "items/warped_sign",
  oak_hanging_sign: "items/oak_hanging_sign",
  spruce_hanging_sign: "items/spruce_hanging_sign",
  birch_hanging_sign: "items/birch_hanging_sign",
  jungle_hanging_sign: "items/jungle_hanging_sign",
  acacia_hanging_sign: "items/acacia_hanging_sign",
  cherry_hanging_sign: "items/cherry_hanging_sign",
  dark_oak_hanging_sign: "items/dark_oak_hanging_sign",
  mangrove_hanging_sign: "items/mangrove_hanging_sign",
  bamboo_hanging_sign: "items/bamboo_hanging_sign",
  crimson_hanging_sign: "items/crimson_hanging_sign",
  warped_hanging_sign: "items/warped_hanging_sign",
  bucket: "items/bucket",
  water_bucket: "items/water_bucket",
  lava_bucket: "items/lava_bucket",
  powder_snow_bucket: "items/powder_snow_bucket",
  snowball: "items/snowball",
  leather: "items/leather",
  milk_bucket: "items/milk_bucket",
  pufferfish_bucket: "items/pufferfish_bucket",
  salmon_bucket: "items/salmon_bucket",
  cod_bucket: "items/cod_bucket",
  tropical_fish_bucket: "items/tropical_fish_bucket",
  axolotl_bucket: "items/axolotl_bucket",
  tadpole_bucket: "items/tadpole_bucket",
  brick: "items/brick",
  clay_ball: "items/clay_ball",
  dried_kelp_block: "block/dried_kelp_side",
  paper: "items/paper",
  book: "items/book",
  slime_ball: "items/slime_ball",
  egg: "items/egg",
  compass: "items/compass_16",
  recovery_compass: "items/recovery_compass_16",
  bundle: "items/bundle",
  fishing_rod: "items/fishing_rod",
  clock: "items/clock_00",
  spyglass: "items/spyglass",
  glowstone_dust: "items/glowstone_dust",
  cod: "items/cod",
  salmon: "items/salmon",
  tropical_fish: "items/tropical_fish",
  pufferfish: "items/pufferfish",
  cooked_cod: "items/cooked_cod",
  cooked_salmon: "items/cooked_salmon",
  ink_sac: "items/ink_sac",
  glow_ink_sac: "items/glow_ink_sac",
  cocoa_beans: "items/cocoa_beans",
  white_dye: "items/white_dye",
  orange_dye: "items/orange_dye",
  magenta_dye: "items/magenta_dye",
  light_blue_dye: "items/light_blue_dye",
  yellow_dye: "items/yellow_dye",
  lime_dye: "items/lime_dye",
  pink_dye: "items/pink_dye",
  gray_dye: "items/gray_dye",
  light_gray_dye: "items/light_gray_dye",
  cyan_dye: "items/cyan_dye",
  purple_dye: "items/purple_dye",
  blue_dye: "items/blue_dye",
  brown_dye: "items/brown_dye",
  green_dye: "items/green_dye",
  red_dye: "items/red_dye",
  black_dye: "items/black_dye",
  bone_meal: "items/bone_meal",
  bone: "items/bone",
  sugar: "items/sugar",
  cake: "items/cake",
  white_bed: "block/white_wool",
  orange_bed: "block/orange_wool",
  magenta_bed: "block/magenta_wool",
  light_blue_bed: "block/light_blue_wool",
  yellow_bed: "block/yellow_wool",
  lime_bed: "block/lime_wool",
  pink_bed: "block/pink_wool",
  gray_bed: "block/gray_wool",
  light_gray_bed: "block/light_gray_wool",
  cyan_bed: "block/cyan_wool",
  purple_bed: "block/purple_wool",
  blue_bed: "block/blue_wool",
  brown_bed: "block/brown_wool",
  green_bed: "block/green_wool",
  red_bed: "block/red_wool",
  black_bed: "block/black_wool",
  cookie: "items/cookie",
  crafter: "block/crafter_bottom",
  filled_map: "items/filled_map",
  shears: "items/shears",
  melon_slice: "items/melon_slice",
  dried_kelp: "items/dried_kelp",
  pumpkin_seeds: "items/pumpkin_seeds",
  melon_seeds: "items/melon_seeds",
  beef: "items/beef",
  cooked_beef: "items/cooked_beef",
  chicken: "items/chicken",
  cooked_chicken: "items/cooked_chicken",
  rotten_flesh: "items/rotten_flesh",
  ender_pearl: "items/ender_pearl",
  blaze_rod: "items/blaze_rod",
  ghast_tear: "items/ghast_tear",
  gold_nugget: "items/gold_nugget",
  nether_wart: "items/nether_wart",
  potion: "items/potion_overlay",
  glass_bottle: "items/glass_bottle",
  spider_eye: "items/spider_eye",
  fermented_spider_eye: "items/fermented_spider_eye",
  blaze_powder: "items/blaze_powder",
  magma_cream: "items/magma_cream",
  brewing_stand: "items/brewing_stand",
  cauldron: "items/cauldron",
  ender_eye: "items/ender_eye",
  glistering_melon_slice: "items/glistering_melon_slice",
  armadillo_spawn_egg: "items/spawn_egg",
  allay_spawn_egg: "items/spawn_egg",
  axolotl_spawn_egg: "items/spawn_egg",
  bat_spawn_egg: "items/spawn_egg",
  bee_spawn_egg: "items/spawn_egg",
  blaze_spawn_egg: "items/spawn_egg",
  bogged_spawn_egg: "items/spawn_egg",
  breeze_spawn_egg: "items/spawn_egg",
  cat_spawn_egg: "items/spawn_egg",
  camel_spawn_egg: "items/spawn_egg",
  cave_spider_spawn_egg: "items/spawn_egg",
  chicken_spawn_egg: "items/spawn_egg",
  cod_spawn_egg: "items/spawn_egg",
  cow_spawn_egg: "items/spawn_egg",
  creeper_spawn_egg: "items/spawn_egg",
  dolphin_spawn_egg: "items/spawn_egg",
  donkey_spawn_egg: "items/spawn_egg",
  drowned_spawn_egg: "items/spawn_egg",
  elder_guardian_spawn_egg: "items/spawn_egg",
  ender_dragon_spawn_egg: "items/spawn_egg",
  enderman_spawn_egg: "items/spawn_egg",
  endermite_spawn_egg: "items/spawn_egg",
  evoker_spawn_egg: "items/spawn_egg",
  fox_spawn_egg: "items/spawn_egg",
  frog_spawn_egg: "items/spawn_egg",
  ghast_spawn_egg: "items/spawn_egg",
  glow_squid_spawn_egg: "items/spawn_egg",
  goat_spawn_egg: "items/spawn_egg",
  guardian_spawn_egg: "items/spawn_egg",
  hoglin_spawn_egg: "items/spawn_egg",
  horse_spawn_egg: "items/spawn_egg",
  husk_spawn_egg: "items/spawn_egg",
  iron_golem_spawn_egg: "items/spawn_egg",
  llama_spawn_egg: "items/spawn_egg",
  magma_cube_spawn_egg: "items/spawn_egg",
  mooshroom_spawn_egg: "items/spawn_egg",
  mule_spawn_egg: "items/spawn_egg",
  ocelot_spawn_egg: "items/spawn_egg",
  panda_spawn_egg: "items/spawn_egg",
  parrot_spawn_egg: "items/spawn_egg",
  phantom_spawn_egg: "items/spawn_egg",
  pig_spawn_egg: "items/spawn_egg",
  piglin_spawn_egg: "items/spawn_egg",
  piglin_brute_spawn_egg: "items/spawn_egg",
  pillager_spawn_egg: "items/spawn_egg",
  polar_bear_spawn_egg: "items/spawn_egg",
  pufferfish_spawn_egg: "items/spawn_egg",
  rabbit_spawn_egg: "items/spawn_egg",
  ravager_spawn_egg: "items/spawn_egg",
  salmon_spawn_egg: "items/spawn_egg",
  sheep_spawn_egg: "items/spawn_egg",
  shulker_spawn_egg: "items/spawn_egg",
  silverfish_spawn_egg: "items/spawn_egg",
  skeleton_spawn_egg: "items/spawn_egg",
  skeleton_horse_spawn_egg: "items/spawn_egg",
  slime_spawn_egg: "items/spawn_egg",
  sniffer_spawn_egg: "items/spawn_egg",
  snow_golem_spawn_egg: "items/spawn_egg",
  spider_spawn_egg: "items/spawn_egg",
  squid_spawn_egg: "items/spawn_egg",
  stray_spawn_egg: "items/spawn_egg",
  strider_spawn_egg: "items/spawn_egg",
  tadpole_spawn_egg: "items/spawn_egg",
  trader_llama_spawn_egg: "items/spawn_egg",
  tropical_fish_spawn_egg: "items/spawn_egg",
  turtle_spawn_egg: "items/spawn_egg",
  vex_spawn_egg: "items/spawn_egg",
  villager_spawn_egg: "items/spawn_egg",
  vindicator_spawn_egg: "items/spawn_egg",
  wandering_trader_spawn_egg: "items/spawn_egg",
  warden_spawn_egg: "items/spawn_egg",
  witch_spawn_egg: "items/spawn_egg",
  wither_spawn_egg: "items/spawn_egg",
  wither_skeleton_spawn_egg: "items/spawn_egg",
  wolf_spawn_egg: "items/spawn_egg",
  zoglin_spawn_egg: "items/spawn_egg",
  zombie_spawn_egg: "items/spawn_egg",
  zombie_horse_spawn_egg: "items/spawn_egg",
  zombie_villager_spawn_egg: "items/spawn_egg",
  zombified_piglin_spawn_egg: "items/spawn_egg",
  experience_bottle: "items/experience_bottle",
  fire_charge: "items/fire_charge",
  wind_charge: "items/wind_charge",
  writable_book: "items/writable_book",
  written_book: "items/written_book",
  mace: "items/mace",
  item_frame: "items/item_frame",
  glow_item_frame: "items/glow_item_frame",
  flower_pot: "items/flower_pot",
  carrot: "items/carrot",
  potato: "items/potato",
  baked_potato: "items/baked_potato",
  poisonous_potato: "items/poisonous_potato",
  map: "items/map",
  golden_carrot: "items/golden_carrot",
  skeleton_skull: "block/soul_sand",
  wither_skeleton_skull: "block/soul_sand",
  player_head: "block/soul_sand",
  zombie_head: "block/soul_sand",
  creeper_head: "block/soul_sand",
  dragon_head: "block/soul_sand",
  piglin_head: "block/soul_sand",
  nether_star: "items/nether_star",
  pumpkin_pie: "items/pumpkin_pie",
  firework_rocket: "items/firework_rocket",
  firework_star: "items/firework_star",
  enchanted_book: "items/enchanted_book",
  nether_brick: "items/nether_brick",
  prismarine_shard: "items/prismarine_shard",
  prismarine_crystals: "items/prismarine_crystals",
  rabbit: "items/rabbit",
  cooked_rabbit: "items/cooked_rabbit",
  rabbit_stew: "items/rabbit_stew",
  rabbit_foot: "items/rabbit_foot",
  rabbit_hide: "items/rabbit_hide",
  armor_stand: "items/armor_stand",
  iron_horse_armor: "items/iron_horse_armor",
  golden_horse_armor: "items/golden_horse_armor",
  diamond_horse_armor: "items/diamond_horse_armor",
  leather_horse_armor: "items/leather_horse_armor",
  lead: "items/lead",
  name_tag: "items/name_tag",
  command_block_minecart: "items/command_block_minecart",
  mutton: "items/mutton",
  cooked_mutton: "items/cooked_mutton",
  white_banner: "block/oak_planks",
  orange_banner: "block/oak_planks",
  magenta_banner: "block/oak_planks",
  light_blue_banner: "block/oak_planks",
  yellow_banner: "block/oak_planks",
  lime_banner: "block/oak_planks",
  pink_banner: "block/oak_planks",
  gray_banner: "block/oak_planks",
  light_gray_banner: "block/oak_planks",
  cyan_banner: "block/oak_planks",
  purple_banner: "block/oak_planks",
  blue_banner: "block/oak_planks",
  brown_banner: "block/oak_planks",
  green_banner: "block/oak_planks",
  red_banner: "block/oak_planks",
  black_banner: "block/oak_planks",
  end_crystal: "items/end_crystal",
  chorus_fruit: "items/chorus_fruit",
  popped_chorus_fruit: "items/popped_chorus_fruit",
  torchflower_seeds: "items/torchflower_seeds",
  pitcher_pod: "items/pitcher_pod",
  beetroot: "items/beetroot",
  beetroot_seeds: "items/beetroot_seeds",
  beetroot_soup: "items/beetroot_soup",
  dragon_breath: "items/dragon_breath",
  splash_potion: "items/potion_overlay",
  spectral_arrow: "items/spectral_arrow",
  tipped_arrow: "items/tipped_arrow_head",
  lingering_potion: "items/potion_overlay",
  shield: "block/dark_oak_planks",
  totem_of_undying: "items/totem_of_undying",
  shulker_shell: "items/shulker_shell",
  iron_nugget: "items/iron_nugget",
  knowledge_book: "items/knowledge_book",
  debug_stick: "items/stick",
  music_disc_13: "items/music_disc_13",
  music_disc_cat: "items/music_disc_cat",
  music_disc_blocks: "items/music_disc_blocks",
  music_disc_chirp: "items/music_disc_chirp",
  music_disc_creator: "items/music_disc_creator",
  music_disc_creator_music_box: "items/music_disc_creator_music_box",
  music_disc_far: "items/music_disc_far",
  music_disc_mall: "items/music_disc_mall",
  music_disc_mellohi: "items/music_disc_mellohi",
  music_disc_stal: "items/music_disc_stal",
  music_disc_strad: "items/music_disc_strad",
  music_disc_ward: "items/music_disc_ward",
  music_disc_11: "items/music_disc_11",
  music_disc_wait: "items/music_disc_wait",
  music_disc_otherside: "items/music_disc_otherside",
  music_disc_relic: "items/music_disc_relic",
  music_disc_5: "items/music_disc_5",
  music_disc_pigstep: "items/music_disc_pigstep",
  music_disc_precipice: "items/music_disc_precipice",
  disc_fragment_5: "items/disc_fragment_5",
  trident: "items/trident",
  phantom_membrane: "items/phantom_membrane",
  nautilus_shell: "items/nautilus_shell",
  heart_of_the_sea: "items/heart_of_the_sea",
  crossbow: "items/crossbow_standby",
  suspicious_stew: "items/suspicious_stew",
  loom: "block/loom_bottom",
  flower_banner_pattern: "items/flower_banner_pattern",
  creeper_banner_pattern: "items/creeper_banner_pattern",
  skull_banner_pattern: "items/skull_banner_pattern",
  mojang_banner_pattern: "items/mojang_banner_pattern",
  globe_banner_pattern: "items/globe_banner_pattern",
  piglin_banner_pattern: "items/piglin_banner_pattern",
  flow_banner_pattern: "items/flow_banner_pattern",
  guster_banner_pattern: "items/guster_banner_pattern",
  goat_horn: "items/goat_horn",
  composter: "block/composter_side",
  barrel: "block/barrel_bottom",
  smoker: "block/smoker_bottom",
  blast_furnace: "block/blast_furnace_front",
  cartography_table: "block/dark_oak_planks",
  fletching_table: "block/birch_planks",
  grindstone: "block/grindstone_pivot",
  smithing_table: "block/smithing_table_bottom",
  stonecutter: "block/stonecutter_bottom",
  bell: "items/bell",
  lantern: "items/lantern",
  soul_lantern: "items/soul_lantern",
  sweet_berries: "items/sweet_berries",
  glow_berries: "items/glow_berries",
  campfire: "items/campfire",
  soul_campfire: "items/soul_campfire",
  shroomlight: "block/shroomlight",
  honeycomb: "items/honeycomb",
  bee_nest: "block/bee_nest_bottom",
  beehive: "block/beehive_end",
  honey_bottle: "items/honey_bottle",
  honeycomb_block: "block/honeycomb_block",
  lodestone: "block/lodestone_top",
  crying_obsidian: "block/crying_obsidian",
  blackstone: "block/blackstone_top",
  blackstone_slab: "block/blackstone_top",
  blackstone_stairs: "block/blackstone_top",
  gilded_blackstone: "block/gilded_blackstone",
  polished_blackstone: "block/polished_blackstone",
  polished_blackstone_slab: "block/polished_blackstone",
  polished_blackstone_stairs: "block/polished_blackstone",
  chiseled_polished_blackstone: "block/chiseled_polished_blackstone",
  polished_blackstone_bricks: "block/polished_blackstone_bricks",
  polished_blackstone_brick_slab: "block/polished_blackstone_bricks",
  polished_blackstone_brick_stairs: "block/polished_blackstone_bricks",
  cracked_polished_blackstone_bricks:
    "block/cracked_polished_blackstone_bricks",
  respawn_anchor: "block/respawn_anchor_bottom",
  candle: "items/candle",
  white_candle: "items/white_candle",
  orange_candle: "items/orange_candle",
  magenta_candle: "items/magenta_candle",
  light_blue_candle: "items/light_blue_candle",
  yellow_candle: "items/yellow_candle",
  lime_candle: "items/lime_candle",
  pink_candle: "items/pink_candle",
  gray_candle: "items/gray_candle",
  light_gray_candle: "items/light_gray_candle",
  cyan_candle: "items/cyan_candle",
  purple_candle: "items/purple_candle",
  blue_candle: "items/blue_candle",
  brown_candle: "items/brown_candle",
  green_candle: "items/green_candle",
  red_candle: "items/red_candle",
  black_candle: "items/black_candle",
  small_amethyst_bud: "block/small_amethyst_bud",
  medium_amethyst_bud: "block/medium_amethyst_bud",
  large_amethyst_bud: "block/large_amethyst_bud",
  amethyst_cluster: "block/amethyst_cluster",
  pointed_dripstone: "items/pointed_dripstone",
  ochre_froglight: "block/ochre_froglight_top",
  verdant_froglight: "block/verdant_froglight_top",
  pearlescent_froglight: "block/pearlescent_froglight_top",
  frogspawn: "block/frogspawn",
  echo_shard: "items/echo_shard",
  brush: "items/brush",
  netherite_upgrade_smithing_template:
    "items/netherite_upgrade_smithing_template",
  sentry_armor_trim_smithing_template:
    "items/sentry_armor_trim_smithing_template",
  dune_armor_trim_smithing_template: "items/dune_armor_trim_smithing_template",
  coast_armor_trim_smithing_template:
    "items/coast_armor_trim_smithing_template",
  wild_armor_trim_smithing_template: "items/wild_armor_trim_smithing_template",
  ward_armor_trim_smithing_template: "items/ward_armor_trim_smithing_template",
  eye_armor_trim_smithing_template: "items/eye_armor_trim_smithing_template",
  vex_armor_trim_smithing_template: "items/vex_armor_trim_smithing_template",
  tide_armor_trim_smithing_template: "items/tide_armor_trim_smithing_template",
  snout_armor_trim_smithing_template:
    "items/snout_armor_trim_smithing_template",
  rib_armor_trim_smithing_template: "items/rib_armor_trim_smithing_template",
  spire_armor_trim_smithing_template:
    "items/spire_armor_trim_smithing_template",
  wayfinder_armor_trim_smithing_template:
    "items/wayfinder_armor_trim_smithing_template",
  shaper_armor_trim_smithing_template:
    "items/shaper_armor_trim_smithing_template",
  silence_armor_trim_smithing_template:
    "items/silence_armor_trim_smithing_template",
  raiser_armor_trim_smithing_template:
    "items/raiser_armor_trim_smithing_template",
  host_armor_trim_smithing_template: "items/host_armor_trim_smithing_template",
  flow_armor_trim_smithing_template: "items/flow_armor_trim_smithing_template",
  bolt_armor_trim_smithing_template: "items/bolt_armor_trim_smithing_template",
  angler_pottery_sherd: "items/angler_pottery_sherd",
  archer_pottery_sherd: "items/archer_pottery_sherd",
  arms_up_pottery_sherd: "items/arms_up_pottery_sherd",
  blade_pottery_sherd: "items/blade_pottery_sherd",
  brewer_pottery_sherd: "items/brewer_pottery_sherd",
  burn_pottery_sherd: "items/burn_pottery_sherd",
  danger_pottery_sherd: "items/danger_pottery_sherd",
  explorer_pottery_sherd: "items/explorer_pottery_sherd",
  flow_pottery_sherd: "items/flow_pottery_sherd",
  friend_pottery_sherd: "items/friend_pottery_sherd",
  guster_pottery_sherd: "items/guster_pottery_sherd",
  heart_pottery_sherd: "items/heart_pottery_sherd",
  heartbreak_pottery_sherd: "items/heartbreak_pottery_sherd",
  howl_pottery_sherd: "items/howl_pottery_sherd",
  miner_pottery_sherd: "items/miner_pottery_sherd",
  mourner_pottery_sherd: "items/mourner_pottery_sherd",
  plenty_pottery_sherd: "items/plenty_pottery_sherd",
  prize_pottery_sherd: "items/prize_pottery_sherd",
  scrape_pottery_sherd: "items/scrape_pottery_sherd",
  sheaf_pottery_sherd: "items/sheaf_pottery_sherd",
  shelter_pottery_sherd: "items/shelter_pottery_sherd",
  skull_pottery_sherd: "items/skull_pottery_sherd",
  snort_pottery_sherd: "items/snort_pottery_sherd",
  copper_grate: "block/copper_grate",
  exposed_copper_grate: "block/exposed_copper_grate",
  weathered_copper_grate: "block/weathered_copper_grate",
  oxidized_copper_grate: "block/oxidized_copper_grate",
  waxed_copper_grate: "block/copper_grate",
  waxed_exposed_copper_grate: "block/exposed_copper_grate",
  waxed_weathered_copper_grate: "block/weathered_copper_grate",
  waxed_oxidized_copper_grate: "block/oxidized_copper_grate",
  copper_bulb: "block/copper_bulb",
  exposed_copper_bulb: "block/exposed_copper_bulb",
  weathered_copper_bulb: "block/weathered_copper_bulb",
  oxidized_copper_bulb: "block/oxidized_copper_bulb",
  waxed_copper_bulb: "block/copper_bulb",
  waxed_exposed_copper_bulb: "block/exposed_copper_bulb",
  waxed_weathered_copper_bulb: "block/weathered_copper_bulb",
  waxed_oxidized_copper_bulb: "block/oxidized_copper_bulb",
  trial_spawner: "block/trial_spawner_bottom",
  trial_key: "items/trial_key",
  ominous_trial_key: "items/ominous_trial_key",
  vault: "block/vault_bottom",
  ominous_bottle: "items/ominous_bottle",
  breeze_rod: "items/breeze_rod",
};
// manual overrides for items whose auto-extracted icon isn't the real inventory icon
const TEXTURE_OVERRIDES = {
  shield: "entity/shield_base_nopattern",
};
function texturePathFor(name) {
  const raw = TEXTURE_OVERRIDES[name] || ITEM_TABLE[name];
  if (!raw) return null;
  return raw.startsWith("block/")
    ? "blocks/" + raw.slice("block/".length)
    : raw;
}
function textureUrlFor(id) {
  if (!id.startsWith("minecraft:")) return null;
  const name = id.slice("minecraft:".length);
  const path = texturePathFor(name);
  if (!path) return null;
  return TEXTURE_BASE + path + ".png";
}

// ---------- fallback emoji guessing (modded / unknown items) ----------
const KEYWORD_ICONS = [
  [/sword/, "⚔️"],
  [/pickaxe/, "⛏️"],
  [/axe/, "🪓"],
  [/shovel/, "🧹"],
  [/hoe/, "🌾"],
  [/crossbow/, "🏹"],
  [/bow/, "🏹"],
  [/arrow/, "➶"],
  [/shield/, "🛡️"],
  [/helmet/, "🪖"],
  [/chestplate/, "🦺"],
  [/leggings/, "👖"],
  [/boots/, "🥾"],
  [/bucket/, "🪣"],
  [/bundle/, "🎒"],
  [/furnace/, "🧱"],
  [/chair|stool|desk|table|sofa|couch/, "🪑"],
  [/bed/, "🛏️"],
  [/wool/, "🧶"],
  [/wood|plank|log|stem/, "🪵"],
  [/wall|brick|stone|cobble|deepslate/, "🧱"],
  [/glass/, "🪟"],
  [/wart/, "🔴"],
  [/netherrack/, "🟧"],
  [/bread|apple|carrot|potato|beef|porkchop|chicken|cod|salmon|stew|pie/, "🍞"],
  [/ingot/, "🔩"],
  [/diamond/, "💎"],
  [/emerald/, "💚"],
  [/gold/, "🟡"],
  [/iron/, "⬜"],
  [/copper/, "🟠"],
  [/coal/, "⚫"],
  [/lead|leash/, "🪢"],
  [/flint_and_steel/, "🔥"],
  [/torch/, "🔥"],
  [/potion/, "🧪"],
  [/book/, "📖"],
  [/map/, "🗺️"],
  [/egg/, "🥚"],
  [/seed/, "🌱"],
  [/flower/, "🌸"],
  [/leaves/, "🍃"],
  [/rail/, "🛤️"],
  [/boat/, "🛶"],
  [/minecart/, "🛒"],
  [/door/, "🚪"],
  [/ladder/, "🪜"],
  [/gunpowder/, "💨"],
  [/obsidian/, "🟪"],
  [/lapis/, "🔵"],
  [/redstone/, "🔴"],
];
function guessEmoji(id) {
  const name = id.includes(":") ? id.split(":")[1] : id;
  for (const [re, icon] of KEYWORD_ICONS) {
    if (re.test(name)) return icon;
  }
  return "📦";
}
function hashColor(str) {
  let h = 0;
  for (let i = 0; i < str.length; i++) h = (h * 31 + str.charCodeAt(i)) >>> 0;
  return `hsl(${h % 360} 45% 45%)`;
}
function formatName(id) {
  const parts = id.split(":");
  const ns = parts.length > 1 ? parts[0] : "minecraft";
  const raw = parts.length > 1 ? parts[1] : parts[0];
  const nice = raw.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
  return { nice, ns };
}
// builds either an <img> (real texture) or a fallback emoji span, appended to `parent`
function appendIcon(parent, id, sizePx) {
  const url = textureUrlFor(id);
  if (url) {
    const img = document.createElement("img");
    img.className = "item-icon";
    img.src = url;
    img.alt = id;
    if (sizePx) {
      img.style.width = sizePx + "px";
      img.style.height = sizePx + "px";
    }
    img.onerror = () => {
      img.remove();
      const span = document.createElement("span");
      span.textContent = guessEmoji(id);
      if (sizePx) span.style.fontSize = Math.round(sizePx * 0.75) + "px";
      parent.appendChild(span);
    };
    parent.appendChild(img);
    return img;
  } else {
    const span = document.createElement("span");
    span.textContent = guessEmoji(id);
    if (sizePx) span.style.fontSize = Math.round(sizePx * 0.75) + "px";
    parent.appendChild(span);
    return span;
  }
}

// ---------- durability tables ----------
const TOOL_DURA = {
  wooden: 59,
  stone: 131,
  iron: 250,
  golden: 32,
  diamond: 1561,
  netherite: 2031,
};
const ARMOR_DURA = {
  leather: { helmet: 55, chestplate: 80, leggings: 75, boots: 65 },
  golden: { helmet: 77, chestplate: 112, leggings: 105, boots: 91 },
  chainmail: { helmet: 165, chestplate: 240, leggings: 225, boots: 195 },
  iron: { helmet: 165, chestplate: 240, leggings: 225, boots: 195 },
  diamond: { helmet: 363, chestplate: 528, leggings: 495, boots: 429 },
  netherite: { helmet: 407, chestplate: 592, leggings: 555, boots: 481 },
  turtle: { helmet: 275 },
};
const SPECIAL_DURA = {
  flint_and_steel: 64,
  shield: 336,
  bow: 384,
  fishing_rod: 64,
  shears: 238,
  trident: 250,
  elytra: 432,
  crossbow: 465,
  carrot_on_a_stick: 25,
  warped_fungus_on_a_stick: 100,
  brush: 64,
  mace: 500,
};
function getMaxDurability(id) {
  const name = id.includes(":") ? id.split(":")[1] : id;
  let m = name.match(
    /^(wooden|stone|iron|golden|diamond|netherite)_(sword|pickaxe|axe|shovel|hoe)$/,
  );
  if (m) return TOOL_DURA[m[1]];
  m = name.match(
    /^(leather|golden|chainmail|iron|diamond|netherite|turtle)_(helmet|chestplate|leggings|boots)$/,
  );
  if (m && ARMOR_DURA[m[1]] && ARMOR_DURA[m[1]][m[2]])
    return ARMOR_DURA[m[1]][m[2]];
  if (SPECIAL_DURA[name] !== undefined) return SPECIAL_DURA[name];
  return null;
}

// ---------- rendering ----------
const invWrap = document.getElementById("invWrap");
const tooltip = document.getElementById("tooltip");
const errorBox = document.getElementById("errorBox");

function makeSlot(item) {
  const slot = document.createElement("div");
  slot.className = "slot";
  if (!item) return slot;

  slot.classList.add("filled");
  const { nice, ns } = formatName(item.id);
  appendIcon(slot, item.id, 30);

  const count = item.count ?? 1;
  if (count > 1) {
    const c = document.createElement("span");
    c.className = "count";
    c.textContent = count;
    slot.appendChild(c);
  }

  const comps = item.components || {};
  const damage = comps["minecraft:damage"];
  const maxDura = getMaxDurability(item.id);
  if (damage !== undefined && maxDura) {
    const remain = Math.max(0, maxDura - damage);
    const pct = Math.max(0, Math.min(1, remain / maxDura));
    const track = document.createElement("div");
    track.className = "durability-track";
    const fill = document.createElement("div");
    fill.className = "durability-fill";
    fill.style.width = pct * 100 + "%";
    fill.style.background =
      pct > 0.5
        ? "var(--hp-green)"
        : pct > 0.2
          ? "var(--hp-yellow)"
          : "var(--hp-red)";
    track.appendChild(fill);
    slot.appendChild(track);
  }

  const bundleContents = comps["minecraft:bundle_contents"];
  if (item.id === "minecraft:bundle" && bundleContents) {
    const total = bundleContents.reduce((s, i) => s + (i.count ?? 1), 0);
    const badge = document.createElement("span");
    badge.className = "bundle-badge";
    badge.textContent = total;
    slot.appendChild(badge);
  }

  slot.addEventListener("mousemove", (e) =>
    showTooltip(e, item, nice, ns, damage, maxDura, bundleContents, count),
  );
  slot.addEventListener("mouseleave", hideTooltip);

  return slot;
}

function showTooltip(
  e,
  item,
  nice,
  ns,
  damage,
  maxDura,
  bundleContents,
  count,
) {
  let html = `<div class="t-name">${nice}</div>`;
  if (ns !== "minecraft") html += `<div class="t-mod">mod: ${ns}</div>`;
  html += `<div class="t-line">count: x${count}</div>`;
  if (damage !== undefined) {
    if (maxDura) {
      const remain = maxDura - damage;
      const pct = remain / maxDura;
      const cls =
        pct > 0.5 ? "t-dura-good" : pct > 0.2 ? "t-dura-mid" : "t-dura-bad";
      html += `<div class="t-line ${cls}">remain: ${remain} / ${maxDura}</div>`;
    } else {
      html += `<div class="t-line">damage: ${damage}</div>`;
    }
  }
  tooltip.innerHTML = html;

  if (item.id === "minecraft:bundle") {
    const wrap = document.createElement("div");
    if (bundleContents && bundleContents.length) {
      const label = document.createElement("div");
      label.className = "t-line";
      label.style.marginTop = "4px";
      label.style.color = "#b899e0";
      label.textContent = "inventory content";
      wrap.appendChild(label);
      bundleContents.forEach((bi) => {
        const bn = formatName(bi.id).nice;
        const line = document.createElement("div");
        line.className = "t-bundle-item";
        appendIcon(line, bi.id, 14);
        const txt = document.createElement("span");
        txt.textContent = `${bn} x${bi.count ?? 1}`;
        line.appendChild(txt);
        wrap.appendChild(line);
      });
    } else {
      const empty = document.createElement("div");
      empty.className = "t-line";
      empty.style.marginTop = "4px";
      empty.textContent = "(Empty)";
      wrap.appendChild(empty);
    }
    tooltip.appendChild(wrap);
  }

  tooltip.style.display = "block";
  positionTooltip(e);
}
function positionTooltip(e) {
  const pad = 16;
  let x = e.clientX + pad,
    y = e.clientY + pad;
  const rect = tooltip.getBoundingClientRect();
  if (x + rect.width > window.innerWidth) x = e.clientX - rect.width - pad;
  if (y + rect.height > window.innerHeight) y = e.clientY - rect.height - pad;
  tooltip.style.left = x + "px";
  tooltip.style.top = y + "px";
}
function hideTooltip() {
  tooltip.style.display = "none";
}
document.addEventListener("mousemove", (e) => {
  if (tooltip.style.display === "block") positionTooltip(e);
});

function buildGrid(slotMap, indices, extraClass) {
  const grid = document.createElement("div");
  grid.className = "grid" + (extraClass ? " " + extraClass : "");
  indices.forEach((i) => grid.appendChild(makeSlot(slotMap[i])));
  return grid;
}

function render(items) {
  invWrap.innerHTML = "";
  if (!items || !items.length) {
    invWrap.innerHTML =
      '<div class="empty-msg">the inventory is empty or invalid json data😕</div>';
    return;
  }
  const slotMap = {};
  items.forEach((it) => {
    slotMap[it.Slot] = it;
  });

  const mainIndices = [];
  for (let r = 0; r < 3; r++)
    for (let c = 0; c < 9; c++) mainIndices.push(9 + r * 9 + c);
  const hotbarIndices = [0, 1, 2, 3, 4, 5, 6, 7, 8];

  const usedSlots = new Set([...mainIndices, ...hotbarIndices]);
  const otherIndices = Object.keys(slotMap)
    .map(Number)
    .filter((s) => !usedSlots.has(s))
    .sort((a, b) => a - b);

  const panel = document.createElement("div");
  panel.className = "panel";
  panel.appendChild(buildGrid(slotMap, mainIndices));
  panel.appendChild(buildGrid(slotMap, hotbarIndices, "hotbar"));
  invWrap.appendChild(panel);

  if (otherIndices.length) {
    const title = document.createElement("div");
    title.className = "section-title";
    title.textContent = "📦 other slots";
    invWrap.appendChild(title);
    const panel2 = document.createElement("div");
    panel2.className = "panel";
    const grid2 = document.createElement("div");
    grid2.className = "grid";
    grid2.style.gridTemplateColumns = `repeat(${Math.min(9, otherIndices.length)}, 42px)`;
    otherIndices.forEach((i) => grid2.appendChild(makeSlot(slotMap[i])));
    panel2.appendChild(grid2);
    invWrap.appendChild(panel2);
  }
}

function tryRender() {
  errorBox.style.display = "none";
  const raw = document.getElementById("jsonInput").value;
  try {
    const jsonStr = relaxedToJSON(raw);
    const items = JSON.parse(jsonStr);
    render(items);
  } catch (err) {
    errorBox.style.display = "block";
    errorBox.textContent = "⚠️ JSON parse error: " + err.message;
    invWrap.innerHTML = "";
  }
}

document.getElementById("renderBtn").addEventListener("click", tryRender);
document.getElementById("sampleBtn").addEventListener("click", () => {
  document.getElementById("jsonInput").value = SAMPLE;
  tryRender();
});

tryRender();
